# AUTHOR : SWETHA SRI.S

# Naive Bayes Classification Algorithim :

## Without Using Library Functions

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("PlayTennis1.csv")

In [3]:
data

     Outlook Play Tennis
0      Sunny          No
1      Sunny          No
2   Overcast         Yes
3       Rain         Yes
4       Rain         Yes
5       Rain          No
6   Overcast         Yes
7      Sunny          No
8      Sunny         Yes
9       Rain         Yes
10     Sunny         Yes
11  Overcast         Yes
12  Overcast         Yes
13      Rain          No

In [4]:
data.shape

(14, 2)

### Frequency Table for the Weather

In [43]:
def weather_freq(o):
    if o=="Sunny":
            sun=data[data.Outlook=="Sunny" ]
            sun_yes=sun[sun['Play Tennis']=="Yes"]['Play Tennis'].count()/data[data['Play Tennis']=="Yes"]['Play Tennis'].count()
            sun_no=sun[sun['Play Tennis']=="No"]['Play Tennis'].count()/data[data['Play Tennis']=="No"]['Play Tennis'].count()
            return sun_yes,sun_no
    if o=="Rain":
            rain=data[data.Outlook=="Rain" ]
            rain_yes=rain[rain['Play Tennis']=="Yes"]['Play Tennis'].count()/data[data['Play Tennis']=="Yes"]['Play Tennis'].count()
            rain_no=rain[rain['Play Tennis']=="No"]['Play Tennis'].count()/data[data['Play Tennis']=="No"]['Play Tennis'].count()
            return rain_yes,rain_no
    if o=="Overcast":
            overcast=data[data.Outlook=="Overcast" ]
            over_yes=overcast[overcast['Play Tennis']=="Yes"]['Play Tennis'].count()/data[data['Play Tennis']=="Yes"]['Play Tennis'].count()
            over_no=overcast[overcast['Play Tennis']=="No"]['Play Tennis'].count()/data[data['Play Tennis']=="No"]['Play Tennis'].count()
            return over_yes,over_no

### Likelihood table and the Probability Prediciton

In [46]:
def likelihood():
    o=input("enter weather")
    res_yes,res_no=weather_freq(o)
    w=data[data.Outlook==o]['Play Tennis'].count()
    yes=data[data['Play Tennis']=="Yes"]['Play Tennis'].count()/data.shape[0]  
    yes_prob=(res_yes*yes)/(w/data.shape[0])
    print(o,"|Yes = ",yes_prob)
    
    
    no=data[data['Play Tennis']=="No"]['Play Tennis'].count()/data.shape[0]
    no_prob=(res_no*no)/(w/data.shape[0])
    print(o,"|No = ",no_prob)
    
    if yes_prob>no_prob:
        print("Class YES has higher probability than class NO =",yes_prob)
    else:
        print("Class NO has higher probability than class YES =",no_prob)

In [47]:
likelihood()

enter weatherSunny
Sunny |Yes =  0.39999999999999997
Sunny |No =  0.6
Class NO has higher probability than class YES = 0.6